In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv('dirty_cafe_sales.csv')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

## Nulos

In [31]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

## Duplicados

In [32]:
print(df[df.duplicated()])

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

## Limpieza de datos

### Renombrar columnas

In [33]:
df.rename(columns={
    'Transaction ID': 'Transaction_ID',
    'Price Per Unit': 'Price_Per_Unit',
    'Total Spent': 'Total_Spent',
    'Payment Method': 'Payment_Method',
    'Transaction Date': 'Transaction_Date'
}, inplace=True)

In [34]:
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

### Convertir a NaN celdas vacías, UNKNOWN y ERROR

In [35]:
a_nan = ['UNKNOWN', 'ERROR', '']
df = df.replace(a_nan, np.nan)
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

### Convertir a fecha la columna 'Transaction_Date'

In [36]:
df['Transaction_Date']=pd.to_datetime(df['Transaction_Date'])

### Extraer año, mes y día de la columna 'Transaction_Date'

In [37]:
df['Year']=df['Transaction_Date'].dt.year
df['Month']=df['Transaction_Date'].dt.month
df['Day']=df['Transaction_Date'].dt.day
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,Year,Month,Day
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,2023.0,9.0,8.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,2023.0,5.0,16.0
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19,2023.0,7.0,19.0
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27,2023.0,4.0,27.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,2023.0,6.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30,2023.0,8.0,30.0
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02,2023.0,6.0,2.0
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02,2023.0,3.0,2.0
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02,2023.0,12.0,2.0
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,2023.0,11.0,7.0

### Convertir a dato numérico las columnas 'Quantity', 'Price_Per_Unit' y 'Total_Spent'

In [38]:
columnas_numericas = ['Quantity', 'Price_Per_Unit', 'Total_Spent']
df[columnas_numericas] = df[columnas_numericas].astype(float)

### Rellenar valores faltantes en columnas 'Quantity', 'Price_Per_Unit' y 'Total_Spent'

In [39]:

# Rellenar Quantity usando Total_Spent / Price_Per_Unit
df['Quantity'] = df['Quantity'].fillna(df['Total_Spent'] / df['Price_Per_Unit'])

# Rellenar Price_Per_Unit usando Total_Spent / Quantity
df['Price_Per_Unit'] = df['Price_Per_Unit'].fillna(df['Total_Spent'] / df['Quantity'])

# Rellenar Total_Spent usando Quantity * Price_Per_Unit
df['Total_Spent'] = df['Total_Spent'].fillna(df['Quantity'] * df['Price_Per_Unit'])

In [40]:
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,Year,Month,Day
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,2023.0,9.0,8.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,2023.0,5.0,16.0
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,2023.0,7.0,19.0
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27,2023.0,4.0,27.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,2023.0,6.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30,2023.0,8.0,30.0
9996,TXN_9659401,NaN,3.0,1.0,3.0,Digital Wallet,NaN,2023-06-02,2023.0,6.0,2.0
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02,2023.0,3.0,2.0
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,NaN,2023-12-02,2023.0,12.0,2.0
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07,2023.0,11.0,7.0

### Rellenar con UNKNOWN valores faltantes en 'Payment_Method' y 'Location'

In [42]:
df['Payment_Method'] = df['Payment_Method'].fillna('UNKNOWN')
df['Location'] = df['Location'].fillna('UNKNOWN')
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,Year,Month,Day
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,2023.0,9.0,8.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,2023.0,5.0,16.0
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,2023.0,7.0,19.0
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,2023.0,4.0,27.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,2023.0,6.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,UNKNOWN,UNKNOWN,2023-08-30,2023.0,8.0,30.0
9996,TXN_9659401,NaN,3.0,1.0,3.0,Digital Wallet,UNKNOWN,2023-06-02,2023.0,6.0,2.0
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,UNKNOWN,2023-03-02,2023.0,3.0,2.0
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,UNKNOWN,2023-12-02,2023.0,12.0,2.0
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07,2023.0,11.0,7.0

In [44]:
eliminar = ['Item', 'Transaction_Date', 'Year', 'Month', 'Day', 'Quantity', 'Price_Per_Unit', 'Total_Spent']

df = df.dropna(subset=eliminar)
df

,Transaction_ID,Item,Quantity,Price_Per_Unit,Total_Spent,Payment_Method,Location,Transaction_Date,Year,Month,Day
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,2023.0,9.0,8.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,2023.0,5.0,16.0
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,2023.0,7.0,19.0
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,2023.0,4.0,27.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,2023.0,6.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,UNKNOWN,2023-10-20,2023.0,10.0,20.0
9995,TXN_7672686,Coffee,2.0,2.0,4.0,UNKNOWN,UNKNOWN,2023-08-30,2023.0,8.0,30.0
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,UNKNOWN,2023-03-02,2023.0,3.0,2.0
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,UNKNOWN,2023-12-02,2023.0,12.0,2.0
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07,2023.0,11.0,7.0

In [45]:
df.to_excel('cafedata_limpio.xlsx', index=False)